apiVersion: v1
kind: ConfigMap

metadata:
  name: coinnews-configs

data:
  config.yml:  |+
    http_port: 8000
    worker_enable: true
    worker_interval: 10
    change_probability: 3
    change_factor: 7
    units:
      - name: bitcoin
        value: 50000
      - name: dogecoin
        value: 23000
      - name: usdcoin
        value: 8000
      - name: zerocoin
        value: 7500
      - name: unocoin
        value: 100
      - name: colocoin
        value: 9240
      - name: somecoin
        value: 80
